/* DisplayFix 模块集中式文本。
 * 变量名按功能和用途命名；修改字符串内容后重新编译。
 * Label是名称，Description/Help是说明，Log是日志，Error/Reason是错误或原因。
 * Button是按钮文字，Value是显示值，Format/Template是保留占位符的文本。
 * 保留格式占位符及其顺序，避免与调用参数不匹配。
 * 本文件编译进 ASI，发行时不需要外置文本文件。 */
#include "DisplayFixText.h"

/* Backend_DaoJian：对应源文件使用的显示文字与诊断信息。 */
const char DisplayFixText_DaoJian_PathConversionFailedValue[] = "[路径转换失败]";
const char DisplayFixText_DaoJian_MissingObjectValue[] = "无";
const char DisplayFixText_DaoJian_PointerLabel[] = "指针=";
const char DisplayFixText_DaoJian_ActiveLabel[] = " 激活=";
const char DisplayFixText_DaoJian_RectLabel[] = " 矩形=";
const char DisplayFixText_DaoJian_InvalidRectValue[] = " 矩形=无效";
const char DisplayFixText_DaoJian_HudCandidateLog[] = "[运行] HUD候选 ";
const char DisplayFixText_DaoJian_StrategyEnterStateLog[] = "[运行] Strategy进入 状态=";
const char DisplayFixText_DaoJian_GameplayConfigReadyValue[] = " GAMEPLAY配置=就绪";
const char DisplayFixText_DaoJian_GameplayConfigFailedValue[] = " GAMEPLAY配置=失败";
const char DisplayFixText_DaoJian_ForceReapplyPatchFailedLog[] = "[运行] Strategy进入：强制重应用补丁失败；回退到FRONTEND配置";
const char DisplayFixText_DaoJian_ForceReapplyRestoreFailedLog[] = "[运行] Strategy进入：强制重应用字节恢复失败；0x407000仍保持强制=1";
const char DisplayFixText_DaoJian_StrategyEnterActualResolutionLog[] = "[运行] Strategy进入 原版应用完成 实际=";
const char DisplayFixText_DaoJian_TargetLabel[] = " 目标=";
const char DisplayFixText_DaoJian_ForceReapplyEnabledValue[] = " 强制=1";
const char DisplayFixText_DaoJian_ForceReapplyDisabledValue[] = " 强制=0";
const char DisplayFixText_DaoJian_GameplayResolutionMismatchLog[] = "[运行] Strategy进入：实际分辨率与目标不符；禁用GAMEPLAY HUD/JMM并恢复FRONTEND代码配置";
const char DisplayFixText_DaoJian_StrategyLeaveStateLog[] = "[运行] Strategy退出 原状态=";
const char DisplayFixText_DaoJian_FrontendConfigRestoredValue[] = " FRONTEND配置=已恢复";
const char DisplayFixText_DaoJian_FrontendConfigFailedValue[] = " FRONTEND配置=失败";
const char DisplayFixText_DaoJian_ResetModeResultLabel[] = " 重置模式=4 结果=";
const char DisplayFixText_DaoJian_ActualResolutionLabel[] = " 实际=";

const char DisplayFixText_DaoJian_FrontendResetFailedLog[] = "[运行] Strategy退出：FRONTEND强制重置失败；标题界面可能仍停留在游戏内Surface";
const char DisplayFixText_DaoJian_FrontendOriginalHudLayoutLog[] = "[运行] FRONTEND HUD自动布局：保持原版4:3布局；不执行居中/JMM同步";
const char DisplayFixText_DaoJian_HudLayoutObjectLog[] = "[运行] HUD布局 对象=";
const char DisplayFixText_DaoJian_RootPositionLabel[] = " 根坐标=";
const char DisplayFixText_DaoJian_OffsetLabel[] = " 偏移=";
const char DisplayFixText_DaoJian_IncludedObjectsLabel[] = " 包含=";

const char DisplayFixText_DaoJian_ActiveObjectSuffix[] = " 激活]";
const char DisplayFixText_DaoJian_InactiveObjectSuffix[] = " 未激活]";

const char DisplayFixText_DaoJian_WorldMousePressCoordinatesLog[] = "[运行] 世界鼠标按下 参数坐标=";
const char DisplayFixText_DaoJian_TopLevelIdLabel[] = " 顶层ID=";
const char DisplayFixText_DaoJian_ChildControlLabel[] = " 子控件=";
const char DisplayFixText_DaoJian_WorldInputBlockedLabel[] = " 阻止世界输入=";
const char DisplayFixText_DaoJian_GlobalMouseReleaseCoordinatesLog[] = "[运行] 全局鼠标释放 参数坐标=";
const char DisplayFixText_DaoJian_HitTestCoordinatesLabel[] = " 测试坐标=";
const char DisplayFixText_DaoJian_CursorAvailableValue[] = " 光标=可用";
const char DisplayFixText_DaoJian_CursorArgumentFallbackValue[] = " 光标=回退到参数";

const char DisplayFixText_DaoJian_TargetBeforeLabel[] = " 目标前=";
const char DisplayFixText_DaoJian_TargetAfterLabel[] = " 目标后=";
const char DisplayFixText_DaoJian_NativeResultLabel[] = " 原版结果=";
const char DisplayFixText_DaoJian_FallbackResultLabel[] = " 兜底=";
const char DisplayFixText_DaoJian_HudMouseReleaseCoordinatesLog[] = "[运行] HUD鼠标释放 参数坐标=";
const char DisplayFixText_DaoJian_CursorCoordinatesLabel[] = " 光标=";
const char DisplayFixText_DaoJian_CursorUnavailableValue[] = " 光标=不可用";
const char DisplayFixText_DaoJian_HitTargetLabel[] = " 命中=";
const char DisplayFixText_DaoJian_AttributesTargetBeforeLabel[] = " 目标0B前=";
const char DisplayFixText_DaoJian_AttributesTargetAfterLabel[] = " 目标0B后=";
const char DisplayFixText_DaoJian_SlotUnavailableValue[] = "槽不可用";
const char DisplayFixText_DaoJian_InventoryTargetBeforeLabel[] = " 目标0E前=";
const char DisplayFixText_DaoJian_InventoryTargetAfterLabel[] = " 目标0E后=";

const char DisplayFixText_DaoJian_JmmApplyModeLog[] = "[运行] JMM应用 模式=";
const char DisplayFixText_DaoJian_InputResolutionLabel[] = " 输入=";
const char DisplayFixText_DaoJian_FinalResolutionLabel[] = " 最终=";
const char DisplayFixText_DaoJian_StartupUiBroadcastSkippedLog[] = "[运行] 启动期UI广播已跳过：前置条件不可用";
const char DisplayFixText_DaoJian_StartupUiBroadcastManagerLog[] = "[运行] 启动期UI广播开始 管理器=";

const char DisplayFixText_DaoJian_StartupUiBroadcastVisitedLog[] = "[运行] 启动期UI广播结束 已遍历=";
const char DisplayFixText_DaoJian_AppliedCountLabel[] = " 已应用=";
const char DisplayFixText_DaoJian_ExceptionGuardTriggeredValue[] = " 保护=命中";
const char DisplayFixText_DaoJian_ExceptionGuardNormalValue[] = " 保护=正常";
const char DisplayFixText_DaoJian_SteamDetectedLateLog[] = "[运行] 延迟检测到Steam环境：ComeOn.dll现已加载";
const char DisplayFixText_DaoJian_SteamJmmWaitingForResourcesLog[] = "[运行] Steam延迟JMM应用等待中：游戏资源根节点尚未就绪";
const char DisplayFixText_DaoJian_SteamJmmApplyAttemptLog[] = "[运行] Steam延迟JMM应用开始 尝试次数=";
const char DisplayFixText_DaoJian_ManagerLabel[] = " 管理器=";
const char DisplayFixText_DaoJian_HeadNodeLabel[] = " 头节点=";

const char DisplayFixText_DaoJian_SteamResourcesReadyAttributesBeforeLabel[] = " 资源根=就绪 ID0B前=";
const char DisplayFixText_DaoJian_InventoryLayoutBeforeLabel[] = " ID0E前=";
const char DisplayFixText_DaoJian_SteamJmmApplyResultLog[] = "[运行] Steam延迟JMM应用结束 结果=";
const char DisplayFixText_DaoJian_ApplyCompletedValue[] = " 完成=1";
const char DisplayFixText_DaoJian_ApplyIncompleteValue[] = " 完成=0";
const char DisplayFixText_DaoJian_ChildLayoutChangedValue[] = " 子布局已变化=1";
const char DisplayFixText_DaoJian_ChildLayoutUnchangedValue[] = " 子布局已变化=0";
const char DisplayFixText_DaoJian_AttributesLayoutAfterLabel[] = " ID0B后=";
const char DisplayFixText_DaoJian_InventoryLayoutAfterLabel[] = " ID0E后=";
const char DisplayFixText_DaoJian_AuxiliaryDrawHookDisabledIdLog[] = "[警告] 辅助GUI绘制层：ID=";
const char DisplayFixText_DaoJian_DrawHookDisableReasonLabel[] = " Draw Hook 已单独禁用；原因=";
const char DisplayFixText_DaoJian_UnknownReasonValue[] = "未知";
const char DisplayFixText_DaoJian_OriginalMenuBehaviorSuffix[] = "；该菜单保持原版绘制/输入";
const char DisplayFixText_DaoJian_AuxiliaryOriginalDrawChainLog[] = "[运行] 辅助GUI原始Draw链 ID=";
const char DisplayFixText_DaoJian_MenuDrawIndexLabel[] = " 菜单索引=";
const char DisplayFixText_DaoJian_HudDrawIndexLabel[] = " 主HUD索引=";
const char DisplayFixText_DaoJian_MenuBeforeHudValue[] = " 关系=菜单在HUD之前；会在HUD之后延迟绘制该菜单";
const char DisplayFixText_DaoJian_MenuAlreadyAfterHudValue[] = " 关系=菜单已在HUD之后；不需要调整该菜单";
const char DisplayFixText_DaoJian_MenuAndHudSameIndexValue[] = " 关系=异常同索引；本帧不会据此修改任何输入状态";
const char DisplayFixText_DaoJian_AuxiliaryPanelTrackingFullLog[] = "[警告] 辅助GUI短生命周期跟踪表已满；额外独立面板保持未跟踪时的原有行为";
const char DisplayFixText_DaoJian_AuxiliaryPanelRetainedAboveHudLog[] = "[运行] 辅助GUI独立面板主窗口关闭后继续置于HUD上方 对象=";
const char DisplayFixText_DaoJian_AuxiliaryDrawHookCapacityLog[] = "[警告] 辅助GUI动态Draw Hook数量已达16类；后续未知辅助面板保持原版绘制";
const char DisplayFixText_DaoJian_HudButtonPressRootCorrectedLog[] = "[运行] 主HUD按钮按压root校正 ID=";
const char DisplayFixText_DaoJian_OriginalRootLabel[] = " 原root=";
const char DisplayFixText_DaoJian_MouseCoordinatesLabel[] = " 鼠标=";
const char DisplayFixText_DaoJian_AuxiliaryInputRootOverrideLog[] = "[运行] 辅助GUI输入root覆盖 HUD->";

const char DisplayFixText_DaoJian_RootRectLabel[] = " root矩形=";
const char DisplayFixText_DaoJian_AuxiliaryDrawOrderChangedLog[] = "[运行] 辅助GUI绘制层调整 ID=";
const char DisplayFixText_DaoJian_MenuDeferredAfterHudSuffix[] = " 原顺序位于主HUD之前；本帧改为HUD之后绘制";
const char DisplayFixText_DaoJian_AuxiliaryPanelDeferredLog[] = "[运行] 辅助GUI独立面板延后绘制 对象=";

const char DisplayFixText_DaoJian_VtableOutsideConfirmedRangeReason[] = "对象 vtable 不在 ComeOn.exe 已确认地址范围";
const char DisplayFixText_DaoJian_DeferredDrawWrapperMissingReason[] = "没有对应的延迟绘制 wrapper";
const char DisplayFixText_DaoJian_InstalledDrawSlotChangedReason[] = "已安装后 target 改用了不同 vtable/Draw 槽";
const char DisplayFixText_DaoJian_NativeDrawOutsideExecutableReason[] = "vtable+0x08 原版 Draw 不在主 EXE .text";
const char DisplayFixText_DaoJian_LayoutFunctionMismatchReason[] = "vtable+0x58 不再指向已确认通用布局函数";
const char DisplayFixText_DaoJian_VtableWriteFailedReason[] = "VirtualProtect/写回 vtable+0x08 失败";
const char DisplayFixText_DaoJian_HudDrawHookMissedFallbackLog[] = "[警告] 辅助GUI图层：本帧预扫描找到主HUD，但HUD Draw未经过Hook；已在帧末安全补画延迟GUI";
const char DisplayFixText_DaoJian_BackendInitializingLog[] = "[DisplayFix] EDSlash统一显示后端";
const char DisplayFixText_DaoJian_GameProfileLoadedLog[] = "[Runtime] 游戏Profile=刀剑封魔录 / DisplayFix后端已加载";
const char DisplayFixText_DaoJian_ArchitectureDescription[] = "架构：Win32/x86 ASI，基于内容签名的运行时补丁";
const char DisplayFixText_DaoJian_VirtualProtectUnavailableLog[] = "[失败] 无法解析 VirtualProtect";
const char DisplayFixText_DaoJian_ExecutableTextSectionUnavailableLog[] = "[失败] 无法定位主 EXE 的 .text 代码段";
const char DisplayFixText_DaoJian_ConfigPathLog[] = "[信息] 配置文件路径=";
const char DisplayFixText_DaoJian_FontDpiPatchAppliedLog[] = "[成功] 字体 DPI 路径已修正为 96 DPI";
const char DisplayFixText_DaoJian_FontDpiPatchAlreadyAppliedLog[] = "[成功] 字体 DPI 路径已经是 96 DPI 修正状态";
const char DisplayFixText_DaoJian_FontDpiSignatureMismatchLog[] = "[失败] 字体 DPI 特征缺失或不唯一；已跳过字体修复";
const char DisplayFixText_DaoJian_FontDpiFixDisabledLog[] = "[信息] Font.FixDPI=0；INI 已关闭字体修复";
const char DisplayFixText_DaoJian_DisplayFixDisabledLog[] = "[信息] Display.Enable=0；已关闭宽屏/HUD/输入补丁；Font.FixDPI 仍独立生效";
const char DisplayFixText_DaoJian_BaseHeightLog[] = "[信息] 基础高度(BaseHeight)=";
const char DisplayFixText_DaoJian_AspectWidthLog[] = "[信息] 比例宽度(AspectWidth)=";
const char DisplayFixText_DaoJian_AspectHeightLog[] = "[信息] 比例高度(AspectHeight)=";
const char DisplayFixText_DaoJian_TargetWidthLog[] = "[信息] 目标宽度(TargetWidth)=";
const char DisplayFixText_DaoJian_TargetWidthAlignmentLog[] = "[信息] AspectRatio目标宽度8像素对齐余数=";
const char DisplayFixText_DaoJian_TargetHeightLog[] = "[信息] 目标高度(TargetHeight)=";
const char DisplayFixText_DaoJian_HighBaseHeightPerformanceWarningLog[] = "[警告] BaseHeight>600 属于高级世界/FOV缩放，可能显著降低帧率";
const char DisplayFixText_DaoJian_RecommendedBaseHeightForFourKLog[] = "[信息] 4K 输出通常建议使用 BaseHeight=480 或 600，再交给 cnc-ddraw 放大";
const char DisplayFixText_DaoJian_NativeBaseWidthLog[] = "[信息] 原生基准宽度(NativeBaseWidth)=";
const char DisplayFixText_DaoJian_MainHudCenterDeltaLog[] = "[信息] 主HUD水平居中偏移(MainHUDCenterDelta)=";
const char DisplayFixText_DaoJian_ResolutionCodeResolvedLog[] = "[成功] 动态分辨率代码点已解析；启动/前端代码保持原样";
const char DisplayFixText_DaoJian_FrontendOriginalResolutionPolicyLog[] = "[信息] 主菜单与固定分辨率动画继续使用游戏原生 4:3 显示生命周期";
const char DisplayFixText_DaoJian_GameplayStrategyResolutionPolicyLog[] = "[信息] 游戏内 TargetWidth/TargetHeight 仅由 Strategy 状态切换激活";
const char DisplayFixText_DaoJian_NativeResolutionMenuLimitLog[] = "[信息] 不需要1024x768菜单选项；游戏菜单最高只提供800x600";
const char DisplayFixText_DaoJian_ResolutionSignatureMismatchLog[] = "[失败] 动态分辨率特征缺失或不唯一；已禁用运行时配置切换";
const char DisplayFixText_DaoJian_FrontendConfigReadyLog[] = "[成功] 前端/动画分辨率配置已就绪：保留原版显示/JMM规则";
const char DisplayFixText_DaoJian_GameplayLayoutEightHundredPolicyLog[] = "[信息] Strategy 状态 3 开始时，游戏内配置会把 TargetWidth 映射到 JMMDL800.txt";
const char DisplayFixText_DaoJian_GameplayLayoutNativePolicyLog[] = "[信息] Strategy 状态 3 开始时，游戏内配置会把 TargetWidth 映射到 JMMDL.txt";
const char DisplayFixText_DaoJian_FrontendConfigSelfTestFailedLog[] = "[失败] 前端配置自检失败；已禁用动态分辨率生命周期";
const char DisplayFixText_DaoJian_JmmSelectorSignatureMismatchLog[] = "[失败] JMM布局选择器特征缺失或不唯一；已禁用运行时布局配置";
const char DisplayFixText_DaoJian_StrategyLifecycleHooksInstalledLog[] = "[成功] Strategy状态生命周期Hook已安装：进入状态3=GAMEPLAY（强制重应用），退出状态3=FRONTEND（强制模式4）";
const char DisplayFixText_DaoJian_ForceReapplyLifecyclePolicyLog[] = "[信息] 进入时：原版0x407000会被临时强制一次；退出时：Strategy清理后强制应用原版显示模式4";
const char DisplayFixText_DaoJian_StrategyLifecycleSignatureMismatchLog[] = "[失败] Strategy状态切换特征/调用缺失或不唯一；已禁用游戏内分辨率切换";
const char DisplayFixText_DaoJian_SteamEnvironmentDetectedLog[] = "[信息] 已检测到Steam/ComeOn.dll环境";
const char DisplayFixText_DaoJian_SteamDeferredJmmReadyLog[] = "[成功] Steam延迟JMM应用已就绪；等待HUD、顶层UI和资源根节点全部成熟";
const char DisplayFixText_DaoJian_SteamNativeJmmApplyPolicyLog[] = "[信息] Steam修复只复用一次原版0x4B35F0；非Steam路径保持不变";
const char DisplayFixText_DaoJian_SteamJmmContextUnavailableLog[] = "[失败] 已检测到Steam环境，但UI/JMM上下文特征缺失或不唯一；已禁用Steam布局同步";
const char DisplayFixText_DaoJian_NonSteamEnvironmentDetectedLog[] = "[信息] 已检测到非Steam环境；Steam延迟UI同步保持休眠";
const char DisplayFixText_DaoJian_OptionalSteamContextUnavailableLog[] = "[信息] 可选Steam UI/JMM上下文未解析；不影响非Steam路径";
const char DisplayFixText_DaoJian_MainHudCenterHookInstalledLog[] = "[成功] 底部主HUD视觉居中Hook已安装";
const char DisplayFixText_DaoJian_MainHudCenterDisabledDiagnosticsLog[] = "[信息] GUI.CenterMainHUD=0；已关闭视觉居中，但HUD诊断仍会安装";
const char DisplayFixText_DaoJian_MainHudLayoutHookInstalledLog[] = "[成功] 主HUD Hook已安装：FRONTEND保持原布局；仅通过Strategy GAMEPLAY门控后在+0x58执行居中/同步";
const char DisplayFixText_DaoJian_MainHudButtonsResolvedLog[] = "[成功] 已解析主HUD +0x24结构并确认顶部按钮ID 0x0B/0x0E；+0x24本身不做Hook";
const char DisplayFixText_DaoJian_EdgeAnchoredUiPolicyLog[] = "[信息] 边缘锚定的顶层UI按设计保持不变";
const char DisplayFixText_DaoJian_MainHudValidationFailedLog[] = "[失败] 主HUD根对象/事件/布局特征验证失败；已跳过HUD Hook";
const char DisplayFixText_DaoJian_HudSharedHooksInstalledLog[] = "[成功] HUD/UI共享输入与绘制基础Hook已安装；0x0B/0x0E按压动画使用原版root路径恢复";
const char DisplayFixText_DaoJian_AuxiliaryUiHooksInstalledLog[] = "[成功] 辅助GUI绘制与输入优先级Hook已安装";
const char DisplayFixText_DaoJian_AuxiliaryDrawChainPolicyLog[] = "[信息] 辅助GUI不改顶层链和对象前后链，只调整当前绘制与输入root选择";
const char DisplayFixText_DaoJian_AuxiliaryInputRootPolicyLog[] = "[信息] 输入只在原版picker已经选中主HUD、且鼠标命中已延后绘制的活动菜单root时覆盖这一次返回值；manager+0x40仍由原版0x4B44D0更新";
const char DisplayFixText_DaoJian_AuxiliaryPanelWrapperPolicyLog[] = "[信息] 当前菜单体系里与HUD相交的独立顶层辅助面板会动态安装Draw wrapper，并按原Draw链顺序在HUD后绘制";
const char DisplayFixText_DaoJian_AuxiliaryPanelLifetimePolicyLog[] = "[信息] 独立辅助面板一旦在合法菜单上下文中确认，会做短生命周期跟踪；主窗口先关闭时，只要面板自身仍active且仍与HUD相交，就继续保持HUD上方";
const char DisplayFixText_DaoJian_NativeHudSpecialPassPolicyLog[] = "[信息] UI manager 的原版HUD特殊绘制pass保持原样，只执行一次；不Hook、不重放该pass";
const char DisplayFixText_DaoJian_AuxiliaryUiStatePreservationLog[] = "[信息] 辅助GUI不改X/Y、child、active、GetCursorPos、self+0xA8、键盘快捷键或按钮业务";
const char DisplayFixText_DaoJian_AuxiliaryUiAboveHudDisabledLog[] = "[信息] GUI.AuxiliaryUIAboveHUD=0；辅助GUI保持原版绘制层/菜单root优先级";
const char DisplayFixText_DaoJian_HudPressRootCorrectionPolicyLog[] = "[信息] 0x0B/0x0E HUD按压root校正仍保留，因为它属于CenterMainHUD输入反馈兼容，不属于辅助GUI图层开关";
const char DisplayFixText_DaoJian_HudSharedHooksDisabledLog[] = "[信息] GUI.CenterMainHUD=0；主HUD未居中，因此不安装HUD/UI共享root与绘制Hook";
const char DisplayFixText_DaoJian_HudSharedHooksValidationFailedLog[] = "[警告] HUD/UI共享root与绘制Hook结构验证失败；按压动画校正和辅助GUI保持原版行为";
const char DisplayFixText_DaoJian_WorldMousePressGuardInstalledLog[] = "[成功] 世界鼠标按下保护已安装，仅用于防止0x0B/0x0E点击穿透";
const char DisplayFixText_DaoJian_NativeMousePressDispatchPolicyLog[] = "[信息] 原版0x4B44F0 UI按下分发保持完全不变";
const char DisplayFixText_DaoJian_WorldMousePressCallsiteMismatchLog[] = "[失败] 世界鼠标按下调用点验证失败；已跳过防点击穿透保护";
const char DisplayFixText_DaoJian_GlobalMouseReleaseGuardInstalledLog[] = "[成功] 全局鼠标释放保护已安装，在HUD路由前处理顶部按钮0x0B/0x0E";
const char DisplayFixText_DaoJian_MouseReleaseFallbackPolicyLog[] = "[信息] 鼠标释放：始终先执行原版UI分发；只有目标激活状态未变化时才执行兜底切换";
const char DisplayFixText_DaoJian_GlobalMouseReleaseCallsiteMismatchLog[] = "[失败] 全局鼠标释放调用点验证失败；已跳过顶部按钮路由前兜底";
/* Backend_WaiZhuan：对应源文件使用的显示文字与诊断信息。 */
const char DisplayFixText_WaiZhuan_PathConversionFailedValue[] = "[路径转换失败]";
const char DisplayFixText_WaiZhuan_SteamResJmRedirectLog[] = "[运行] Steam原始ResJM.Lib重定向 -> ";

const char DisplayFixText_WaiZhuan_SteamResJmRedirectSucceededValue[] = " 结果=成功";
const char DisplayFixText_WaiZhuan_SteamResJmRedirectFailedValue[] = " 结果=失败；继续尝试原始文件";
const char DisplayFixText_WaiZhuan_MissingObjectValue[] = "无";
const char DisplayFixText_WaiZhuan_PointerLabel[] = "指针=";
const char DisplayFixText_WaiZhuan_ActiveLabel[] = " 激活=";
const char DisplayFixText_WaiZhuan_RectLabel[] = " 矩形=";
const char DisplayFixText_WaiZhuan_InvalidRectValue[] = " 矩形=无效";
const char DisplayFixText_WaiZhuan_HudCandidateLog[] = "[运行] HUD候选 ";
const char DisplayFixText_WaiZhuan_SteamWindowClassAtomGuardHitCountLog[] = "[运行] Steam CreateWindowExA 类Atom保护命中次数=";
const char DisplayFixText_WaiZhuan_LastWindowClassAtomLabel[] = " 最后Atom=";
const char DisplayFixText_WaiZhuan_StrategyEnterStateLog[] = "[运行] Strategy进入 状态=";
const char DisplayFixText_WaiZhuan_GameplayConfigReadyValue[] = " GAMEPLAY配置=就绪";
const char DisplayFixText_WaiZhuan_GameplayConfigFailedValue[] = " GAMEPLAY配置=失败";
const char DisplayFixText_WaiZhuan_ForceReapplyPatchFailedLog[] = "[运行] Strategy进入：强制重应用补丁失败；回退到FRONTEND配置";
const char DisplayFixText_WaiZhuan_ForceReapplyRestoreFailedLog[] = "[运行] Strategy进入：强制重应用恢复失败；Strategy进入流程仍保持强制=1";
const char DisplayFixText_WaiZhuan_StrategyEnterActualResolutionLog[] = "[运行] Strategy进入 原版应用完成 实际=";
const char DisplayFixText_WaiZhuan_TargetLabel[] = " 目标=";
const char DisplayFixText_WaiZhuan_ForceReapplyEnabledValue[] = " 强制=1";
const char DisplayFixText_WaiZhuan_ForceReapplyDisabledValue[] = " 强制=0";
const char DisplayFixText_WaiZhuan_GameplayResolutionMismatchLog[] = "[运行] Strategy进入：实际分辨率与目标不符；禁用GAMEPLAY HUD/JMM并恢复FRONTEND代码配置";
const char DisplayFixText_WaiZhuan_StrategyLeaveStateLog[] = "[运行] Strategy退出 原状态=";
const char DisplayFixText_WaiZhuan_FrontendConfigRestoredValue[] = " FRONTEND配置=已恢复";
const char DisplayFixText_WaiZhuan_FrontendConfigFailedValue[] = " FRONTEND配置=失败";
const char DisplayFixText_WaiZhuan_ResetModeResultLabel[] = " 重置模式=4 结果=";
const char DisplayFixText_WaiZhuan_ActualResolutionLabel[] = " 实际=";

const char DisplayFixText_WaiZhuan_FrontendResetFailedLog[] = "[运行] Strategy退出：FRONTEND强制重置失败；标题界面可能仍停留在游戏内Surface";
const char DisplayFixText_WaiZhuan_FrontendOriginalHudLayoutLog[] = "[运行] FRONTEND HUD自动布局：保持原版4:3布局；不执行居中/JMM同步";
const char DisplayFixText_WaiZhuan_HudLayoutObjectLog[] = "[运行] HUD布局 对象=";
const char DisplayFixText_WaiZhuan_RootPositionLabel[] = " 根坐标=";
const char DisplayFixText_WaiZhuan_OffsetLabel[] = " 偏移=";
const char DisplayFixText_WaiZhuan_IncludedObjectsLabel[] = " 包含=";

const char DisplayFixText_WaiZhuan_ActiveObjectSuffix[] = " 激活]";
const char DisplayFixText_WaiZhuan_InactiveObjectSuffix[] = " 未激活]";

const char DisplayFixText_WaiZhuan_WorldMousePressCoordinatesLog[] = "[运行] 世界鼠标按下 参数坐标=";
const char DisplayFixText_WaiZhuan_TopLevelIdLabel[] = " 顶层ID=";
const char DisplayFixText_WaiZhuan_ChildControlLabel[] = " 子控件=";
const char DisplayFixText_WaiZhuan_WorldInputBlockedLabel[] = " 阻止世界输入=";
const char DisplayFixText_WaiZhuan_GlobalMouseReleaseCoordinatesLog[] = "[运行] 全局鼠标释放 参数坐标=";
const char DisplayFixText_WaiZhuan_HitTestCoordinatesLabel[] = " 测试坐标=";
const char DisplayFixText_WaiZhuan_CursorAvailableValue[] = " 光标=可用";
const char DisplayFixText_WaiZhuan_CursorArgumentFallbackValue[] = " 光标=回退到参数";

const char DisplayFixText_WaiZhuan_TargetBeforeLabel[] = " 目标前=";
const char DisplayFixText_WaiZhuan_TargetAfterLabel[] = " 目标后=";
const char DisplayFixText_WaiZhuan_NativeResultLabel[] = " 原版结果=";
const char DisplayFixText_WaiZhuan_FallbackResultLabel[] = " 兜底=";
const char DisplayFixText_WaiZhuan_HudMouseReleaseCoordinatesLog[] = "[运行] HUD鼠标释放 参数坐标=";
const char DisplayFixText_WaiZhuan_CursorCoordinatesLabel[] = " 光标=";
const char DisplayFixText_WaiZhuan_CursorUnavailableValue[] = " 光标=不可用";
const char DisplayFixText_WaiZhuan_HitTargetLabel[] = " 命中=";
const char DisplayFixText_WaiZhuan_AttributesTargetBeforeLabel[] = " 目标0B前=";
const char DisplayFixText_WaiZhuan_AttributesTargetAfterLabel[] = " 目标0B后=";
const char DisplayFixText_WaiZhuan_SlotUnavailableValue[] = "槽不可用";
const char DisplayFixText_WaiZhuan_InventoryTargetBeforeLabel[] = " 目标0E前=";
const char DisplayFixText_WaiZhuan_InventoryTargetAfterLabel[] = " 目标0E后=";

const char DisplayFixText_WaiZhuan_JmmApplyModeLog[] = "[运行] JMM应用 模式=";
const char DisplayFixText_WaiZhuan_InputResolutionLabel[] = " 输入=";
const char DisplayFixText_WaiZhuan_FinalResolutionLabel[] = " 最终=";
const char DisplayFixText_WaiZhuan_StartupUiBroadcastSkippedLog[] = "[运行] 启动期UI广播已跳过：前置条件不可用";
const char DisplayFixText_WaiZhuan_StartupUiBroadcastManagerLog[] = "[运行] 启动期UI广播开始 管理器=";

const char DisplayFixText_WaiZhuan_StartupUiBroadcastVisitedLog[] = "[运行] 启动期UI广播结束 已遍历=";
const char DisplayFixText_WaiZhuan_AppliedCountLabel[] = " 已应用=";
const char DisplayFixText_WaiZhuan_ExceptionGuardTriggeredValue[] = " 保护=命中";
const char DisplayFixText_WaiZhuan_ExceptionGuardNormalValue[] = " 保护=正常";
const char DisplayFixText_WaiZhuan_SteamDetectedLateLog[] = "[运行] 延迟检测到Steam环境：ComeOn.dll现已加载";
const char DisplayFixText_WaiZhuan_SteamJmmWaitingForResourcesLog[] = "[运行] Steam延迟JMM应用等待中：游戏资源根节点尚未就绪";
const char DisplayFixText_WaiZhuan_SteamJmmApplyAttemptLog[] = "[运行] Steam延迟JMM应用开始 尝试次数=";
const char DisplayFixText_WaiZhuan_ManagerLabel[] = " 管理器=";
const char DisplayFixText_WaiZhuan_HeadNodeLabel[] = " 头节点=";

const char DisplayFixText_WaiZhuan_SteamResourcesReadyAttributesBeforeLabel[] = " 资源根=就绪 ID0B前=";
const char DisplayFixText_WaiZhuan_InventoryLayoutBeforeLabel[] = " ID0E前=";
const char DisplayFixText_WaiZhuan_SteamJmmApplyResultLog[] = "[运行] Steam延迟JMM应用结束 结果=";
const char DisplayFixText_WaiZhuan_ApplyCompletedValue[] = " 完成=1";
const char DisplayFixText_WaiZhuan_ApplyIncompleteValue[] = " 完成=0";
const char DisplayFixText_WaiZhuan_ChildLayoutChangedValue[] = " 子布局已变化=1";
const char DisplayFixText_WaiZhuan_ChildLayoutUnchangedValue[] = " 子布局已变化=0";
const char DisplayFixText_WaiZhuan_AttributesLayoutAfterLabel[] = " ID0B后=";
const char DisplayFixText_WaiZhuan_InventoryLayoutAfterLabel[] = " ID0E后=";
const char DisplayFixText_WaiZhuan_AuxiliaryDrawHookDisabledIdLog[] = "[警告] 辅助GUI绘制层：ID=";
const char DisplayFixText_WaiZhuan_DrawHookDisableReasonLabel[] = " Draw Hook 已单独禁用；原因=";
const char DisplayFixText_WaiZhuan_UnknownReasonValue[] = "未知";
const char DisplayFixText_WaiZhuan_OriginalMenuBehaviorSuffix[] = "；该菜单保持原版绘制/输入";
const char DisplayFixText_WaiZhuan_AuxiliaryOriginalDrawChainLog[] = "[运行] 辅助GUI原始Draw链 ID=";
const char DisplayFixText_WaiZhuan_MenuDrawIndexLabel[] = " 菜单索引=";
const char DisplayFixText_WaiZhuan_HudDrawIndexLabel[] = " 主HUD索引=";
const char DisplayFixText_WaiZhuan_MenuBeforeHudValue[] = " 关系=菜单在HUD之前；会在HUD之后延迟绘制该菜单";
const char DisplayFixText_WaiZhuan_MenuAlreadyAfterHudValue[] = " 关系=菜单已在HUD之后；不需要调整该菜单";
const char DisplayFixText_WaiZhuan_MenuAndHudSameIndexValue[] = " 关系=异常同索引；本帧不会据此修改任何输入状态";
const char DisplayFixText_WaiZhuan_AuxiliaryPanelTrackingFullLog[] = "[警告] 辅助GUI短生命周期跟踪表已满；额外独立面板保持未跟踪时的原有行为";
const char DisplayFixText_WaiZhuan_AuxiliaryPanelRetainedAboveHudLog[] = "[运行] 辅助GUI独立面板主窗口关闭后继续置于HUD上方 对象=";
const char DisplayFixText_WaiZhuan_AuxiliaryDrawHookCapacityLog[] = "[警告] 辅助GUI动态Draw Hook数量已达16类；后续未知辅助面板保持原版绘制";
const char DisplayFixText_WaiZhuan_HudButtonPressRootCorrectedLog[] = "[运行] 主HUD按钮按压root校正 ID=";
const char DisplayFixText_WaiZhuan_OriginalRootLabel[] = " 原root=";
const char DisplayFixText_WaiZhuan_MouseCoordinatesLabel[] = " 鼠标=";
const char DisplayFixText_WaiZhuan_AuxiliaryInputRootOverrideLog[] = "[运行] 辅助GUI输入root覆盖 HUD->";

const char DisplayFixText_WaiZhuan_RootRectLabel[] = " root矩形=";
const char DisplayFixText_WaiZhuan_AuxiliaryDrawOrderChangedLog[] = "[运行] 辅助GUI绘制层调整 ID=";
const char DisplayFixText_WaiZhuan_MenuDeferredAfterHudSuffix[] = " 原顺序位于主HUD之前；本帧改为HUD之后绘制";
const char DisplayFixText_WaiZhuan_AuxiliaryPanelDeferredLog[] = "[运行] 辅助GUI独立面板延后绘制 对象=";

const char DisplayFixText_WaiZhuan_VtableOutsideConfirmedRangeReason[] = "对象 vtable 不在 ComeOn.exe 已确认地址范围";
const char DisplayFixText_WaiZhuan_DeferredDrawWrapperMissingReason[] = "没有对应的延迟绘制 wrapper";
const char DisplayFixText_WaiZhuan_InstalledDrawSlotChangedReason[] = "已安装后 target 改用了不同 vtable/Draw 槽";
const char DisplayFixText_WaiZhuan_NativeDrawOutsideExecutableReason[] = "vtable+0x08 原版 Draw 不在主 EXE .text";
const char DisplayFixText_WaiZhuan_LayoutFunctionMismatchReason[] = "vtable+0x58 不再指向已确认通用布局函数";
const char DisplayFixText_WaiZhuan_VtableWriteFailedReason[] = "VirtualProtect/写回 vtable+0x08 失败";
const char DisplayFixText_WaiZhuan_HudDrawHookMissedFallbackLog[] = "[警告] 辅助GUI图层：本帧预扫描找到主HUD，但HUD Draw未经过Hook；已在帧末安全补画延迟GUI";
const char DisplayFixText_WaiZhuan_BackendInitializingLog[] = "[DisplayFix] EDSlash统一显示后端";
const char DisplayFixText_WaiZhuan_GameProfileLoadedLog[] = "[Runtime] 游戏Profile=刀剑封魔录外传：上古传说 / DisplayFix后端已加载";
const char DisplayFixText_WaiZhuan_ArchitectureDescription[] = "架构：Win32/x86 ASI，基于内容签名的运行时补丁";
const char DisplayFixText_WaiZhuan_VirtualProtectUnavailableLog[] = "[失败] 无法解析 VirtualProtect";
const char DisplayFixText_WaiZhuan_ExecutableTextSectionUnavailableLog[] = "[失败] 无法定位主 EXE 的 .text 代码段";
const char DisplayFixText_WaiZhuan_ConfigPathLog[] = "[信息] 配置文件路径=";
const char DisplayFixText_WaiZhuan_FontDpiPatchAppliedLog[] = "[成功] 字体 DPI 路径已修正为 96 DPI";
const char DisplayFixText_WaiZhuan_FontDpiPatchAlreadyAppliedLog[] = "[成功] 字体 DPI 路径已经是 96 DPI 修正状态";
const char DisplayFixText_WaiZhuan_FontDpiSignatureMismatchLog[] = "[失败] 字体 DPI 特征缺失或不唯一；已跳过字体修复";
const char DisplayFixText_WaiZhuan_FontDpiFixDisabledLog[] = "[信息] Font.FixDPI=0；INI 已关闭字体修复";
const char DisplayFixText_WaiZhuan_DisplayFixDisabledLog[] = "[信息] Display.Enable=0；已关闭宽屏/HUD/输入补丁；Font.FixDPI 仍独立生效";
const char DisplayFixText_WaiZhuan_BaseHeightLog[] = "[信息] 基础高度(BaseHeight)=";
const char DisplayFixText_WaiZhuan_AspectWidthLog[] = "[信息] 比例宽度(AspectWidth)=";
const char DisplayFixText_WaiZhuan_AspectHeightLog[] = "[信息] 比例高度(AspectHeight)=";
const char DisplayFixText_WaiZhuan_TargetWidthLog[] = "[信息] 目标宽度(TargetWidth)=";
const char DisplayFixText_WaiZhuan_TargetWidthAlignmentLog[] = "[信息] AspectRatio目标宽度8像素对齐余数=";
const char DisplayFixText_WaiZhuan_TargetHeightLog[] = "[信息] 目标高度(TargetHeight)=";
const char DisplayFixText_WaiZhuan_HighBaseHeightPerformanceWarningLog[] = "[警告] BaseHeight>600 属于高级世界/FOV缩放，可能显著降低帧率";
const char DisplayFixText_WaiZhuan_RecommendedBaseHeightForFourKLog[] = "[信息] 4K 输出通常建议使用 BaseHeight=480 或 600，再交给 cnc-ddraw 放大";
const char DisplayFixText_WaiZhuan_NativeBaseWidthLog[] = "[信息] 原生基准宽度(NativeBaseWidth)=";
const char DisplayFixText_WaiZhuan_MainHudCenterDeltaLog[] = "[信息] 主HUD水平居中偏移(MainHUDCenterDelta)=";
const char DisplayFixText_WaiZhuan_ResolutionCodeResolvedLog[] = "[成功] 动态分辨率代码点已解析；启动/前端代码保持原样";
const char DisplayFixText_WaiZhuan_FrontendOriginalResolutionPolicyLog[] = "[信息] 主菜单与固定分辨率动画继续使用游戏原生 4:3 显示生命周期";
const char DisplayFixText_WaiZhuan_GameplayStrategyResolutionPolicyLog[] = "[信息] 游戏内 TargetWidth/TargetHeight 仅由 Strategy 状态切换激活";
const char DisplayFixText_WaiZhuan_GameplayResolutionBranchRemapPolicyLog[] = "[信息] 不需要隐藏的1024x768分支选择；游戏内会重映射所有已确认的显示模式分支";
const char DisplayFixText_WaiZhuan_ResolutionSignatureMismatchLog[] = "[失败] 动态分辨率特征缺失或不唯一；已禁用运行时配置切换";
const char DisplayFixText_WaiZhuan_FrontendConfigReadyLog[] = "[成功] 前端/动画分辨率配置已就绪：保留原版显示/JMM规则";
const char DisplayFixText_WaiZhuan_GameplayLayoutEightHundredPolicyLog[] = "[信息] Strategy 状态 3 开始时，游戏内配置会把 TargetWidth 映射到 JMMDL800.txt";
const char DisplayFixText_WaiZhuan_GameplayLayoutNativePolicyLog[] = "[信息] Strategy 状态 3 开始时，游戏内配置会把 TargetWidth 映射到 JMMDL.txt";
const char DisplayFixText_WaiZhuan_FrontendConfigSelfTestFailedLog[] = "[失败] 前端配置自检失败；已禁用动态分辨率生命周期";
const char DisplayFixText_WaiZhuan_JmmSelectorSignatureMismatchLog[] = "[失败] JMM布局选择器特征缺失或不唯一；已禁用运行时布局配置";
const char DisplayFixText_WaiZhuan_StrategyLifecycleHooksInstalledLog[] = "[成功] Strategy状态生命周期Hook已安装：进入状态3=GAMEPLAY（强制重应用），退出状态3=FRONTEND（强制模式4）";
const char DisplayFixText_WaiZhuan_ForceReapplyLifecyclePolicyLog[] = "[信息] 进入时：原版Strategy进入流程会被强制重应用一次；退出时：Strategy清理后强制应用原版显示模式4";
const char DisplayFixText_WaiZhuan_StrategyLifecycleSignatureMismatchLog[] = "[失败] Strategy状态切换特征/调用缺失或不唯一；已禁用游戏内分辨率切换";
const char DisplayFixText_WaiZhuan_SteamResJmFileOpenFallbackReadyLog[] = "[成功] Steam多语言 ResJM.Lib CreateFileA 兜底已安装";
const char DisplayFixText_WaiZhuan_SteamResJmFallbackSignatureUnavailableLog[] = "[警告] Steam ResJM.Lib兜底特征尚未就绪或未匹配";
const char DisplayFixText_WaiZhuan_SteamWindowClassAtomFixReadyLog[] = "[成功] Steam ComeOn.dll CreateWindowExA 类Atom兼容修复已安装；官方EDIT处理保持完整";
const char DisplayFixText_WaiZhuan_SteamOpenGlClassNameGuardPolicyLog[] = "[信息] Steam OpenGL兼容修复仅绕过ComeOn.dll对NULL/MAKEINTATOM类名的不安全字符串解析";
const char DisplayFixText_WaiZhuan_SteamWindowClassAtomFixSignatureMismatchLog[] = "[失败] Steam CreateWindowExA callback的Atom保护特征未匹配；ComeOn.dll callback保持原样";
const char DisplayFixText_WaiZhuan_SteamEnvironmentDetectedLog[] = "[信息] 已检测到外传Steam/ComeOn.dll；稳定的显示/HUD时序保持不变";
const char DisplayFixText_WaiZhuan_SteamIntroAnimationOwnershipPolicyLog[] = "[信息] Steam启动器控制的开场动画不属于DisplayFix职责";
const char DisplayFixText_WaiZhuan_NonSteamEnvironmentDetectedLog[] = "[信息] 已检测到外传非Steam环境";
const char DisplayFixText_WaiZhuan_OptionalJmmContextUnavailableLog[] = "[信息] 可选JMM上下文未解析；非Steam核心宽屏路径仍可继续";
const char DisplayFixText_WaiZhuan_MainHudCenterHookInstalledLog[] = "[成功] 底部主HUD视觉居中Hook已安装";
const char DisplayFixText_WaiZhuan_MainHudCenterDisabledDiagnosticsLog[] = "[信息] GUI.CenterMainHUD=0；已关闭视觉居中，但HUD诊断仍会安装";
const char DisplayFixText_WaiZhuan_MainHudLayoutHookInstalledLog[] = "[成功] 主HUD Hook已安装：FRONTEND保持原布局；仅通过Strategy GAMEPLAY门控后在+0x58执行居中/同步";
const char DisplayFixText_WaiZhuan_MainHudButtonsResolvedLog[] = "[成功] 已解析主HUD +0x24结构并确认顶部按钮ID 0x0B/0x0E；+0x24本身不做Hook";
const char DisplayFixText_WaiZhuan_EdgeAnchoredUiPolicyLog[] = "[信息] 边缘锚定的顶层UI按设计保持不变";
const char DisplayFixText_WaiZhuan_MainHudValidationFailedLog[] = "[失败] 主HUD根对象/事件/布局特征验证失败；已跳过HUD Hook";
const char DisplayFixText_WaiZhuan_HudSharedHooksInstalledLog[] = "[成功] HUD/UI共享输入与绘制基础Hook已安装；0x0B/0x0E按压动画使用原版root路径恢复";
const char DisplayFixText_WaiZhuan_AuxiliaryUiHooksInstalledLog[] = "[成功] 辅助GUI绘制与输入优先级Hook已安装";
const char DisplayFixText_WaiZhuan_AuxiliaryDrawChainPolicyLog[] = "[信息] 辅助GUI不改顶层链和对象前后链，只调整当前绘制与输入root选择";
const char DisplayFixText_WaiZhuan_AuxiliaryInputRootPolicyLog[] = "[信息] 输入只在原版picker已经选中主HUD、且鼠标命中已延后绘制的活动菜单root时覆盖这一次返回值；manager+0x40仍由原版0x4B44D0更新";
const char DisplayFixText_WaiZhuan_AuxiliaryPanelWrapperPolicyLog[] = "[信息] 当前菜单体系里与HUD相交的独立顶层辅助面板会动态安装Draw wrapper，并按原Draw链顺序在HUD后绘制";
const char DisplayFixText_WaiZhuan_AuxiliaryPanelLifetimePolicyLog[] = "[信息] 独立辅助面板一旦在合法菜单上下文中确认，会做短生命周期跟踪；主窗口先关闭时，只要面板自身仍active且仍与HUD相交，就继续保持HUD上方";
const char DisplayFixText_WaiZhuan_NativeHudSpecialPassPolicyLog[] = "[信息] UI manager 的原版HUD特殊绘制pass保持原样，只执行一次；不Hook、不重放该pass";
const char DisplayFixText_WaiZhuan_AuxiliaryUiStatePreservationLog[] = "[信息] 辅助GUI不改X/Y、child、active、GetCursorPos、self+0xA8、键盘快捷键或按钮业务";
const char DisplayFixText_WaiZhuan_AuxiliaryUiAboveHudDisabledLog[] = "[信息] GUI.AuxiliaryUIAboveHUD=0；辅助GUI保持原版绘制层/菜单root优先级";
const char DisplayFixText_WaiZhuan_HudPressRootCorrectionPolicyLog[] = "[信息] 0x0B/0x0E HUD按压root校正仍保留，因为它属于CenterMainHUD输入反馈兼容，不属于辅助GUI图层开关";
const char DisplayFixText_WaiZhuan_HudSharedHooksDisabledLog[] = "[信息] GUI.CenterMainHUD=0；主HUD未居中，因此不安装HUD/UI共享root与绘制Hook";
const char DisplayFixText_WaiZhuan_HudSharedHooksValidationFailedLog[] = "[警告] HUD/UI共享root与绘制Hook结构验证失败；按压动画校正和辅助GUI保持原版行为";
const char DisplayFixText_WaiZhuan_WorldMousePressGuardInstalledLog[] = "[成功] 世界鼠标按下保护已安装，仅用于防止0x0B/0x0E点击穿透";
const char DisplayFixText_WaiZhuan_NativeMousePressDispatchPolicyLog[] = "[信息] 原版0x4B44F0 UI按下分发保持完全不变";
const char DisplayFixText_WaiZhuan_WorldMousePressCallsiteMismatchLog[] = "[失败] 世界鼠标按下调用点验证失败；已跳过防点击穿透保护";
const char DisplayFixText_WaiZhuan_GlobalMouseReleaseGuardInstalledLog[] = "[成功] 全局鼠标释放保护已安装，在HUD路由前处理顶部按钮0x0B/0x0E";
const char DisplayFixText_WaiZhuan_MouseReleaseFallbackPolicyLog[] = "[信息] 鼠标释放：始终先执行原版UI分发；只有目标激活状态未变化时才执行兜底切换";
const char DisplayFixText_WaiZhuan_GlobalMouseReleaseCallsiteMismatchLog[] = "[失败] 全局鼠标释放调用点验证失败；已跳过顶部按钮路由前兜底";

/* 英文界面标记与诊断片段同样集中编辑。 */
const char DisplayFixText_DaoJian_ObjectIdLabel[] = " ID=";
const char DisplayFixText_DaoJian_VtableLabel[] = " vtable=";
const char DisplayFixText_DaoJian_HudRootRelationLabel[] = " -> HUD=";
const char DisplayFixText_DaoJian_ChildObjectLabel[] = " child=";

const char DisplayFixText_WaiZhuan_ObjectIdLabel[] = " ID=";
const char DisplayFixText_WaiZhuan_VtableLabel[] = " vtable=";
const char DisplayFixText_WaiZhuan_HudRootRelationLabel[] = " -> HUD=";
const char DisplayFixText_WaiZhuan_ChildObjectLabel[] = " child=";
